default_language_version:
  python: python3.8

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort . 
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [ --force-exclude=/migrations/, --skip-string-normalization, --line-length=119, -v]



      
