default_language_version:
  python: python3.8

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort . 

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black . --exclude="migrations" --skip-string-normalization
        exclude: migrations
        types: [python]



      
