# Generated by Django 3.1.1 on 2020-09-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='labels',
            field=models.ManyToManyField(blank=True, to='blog.BlogPostLabel'),
        ),
    ]
