# Generated by Django 3.1.2 on 2020-10-19 12:12

from django.db import migrations, models

import blog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='uploads/', validators=[blog.validators.validate_file_type]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
