# Generated by Django 3.1.2 on 2020-11-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201019_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_from_file',
            field=models.BooleanField(default=False),
        ),
    ]
