# Generated by Django 3.1.5 on 2021-01-23 19:32

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_is_from_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=martor.models.MartorField(blank=True, null=True),
        ),
    ]
