name: Docker Builds
on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker-build
        run: |
          docker-compose up -d --build
      - name: pytest 
        run: |
          docker-compose -t exec web pytest 
      - name: stop container
        run: |
          docker-compose down
